SARIMA = "SARIMA"
ARIMA = "ARIMA"
SARIMAX = "SARIMAX"
RMSE = "RMSE"
result_dir = "../results/"
MEAN = "Mean"
SOURCE = "Country + Energy"
DATE = "date"
data_dir = "../data/"
predictionCount = 3
ARIMAP = "arima_prediction"
SARIMAP = "sarima_prediction"
FORECAST = "Forecast"
M2 = ["France", "Germany"]  # Major 2
