SARIMA = "SARIMA"
ARIMA = "ARIMA"
SARIMAX = "SARIMAX"
RMSPE = "RMSPE"
MAPE = "MAPE"
ARIMAM = "ARIMA_MAPE"
SARIMAM = "SARIMA_MAPE"
SARIMAXM = "SARIMAX_MAPE"
order = "order"
result_dir = "../results/"
MEAN = "Mean"
SOURCE = "Country + Energy"
DATE = "date"
data_dir = "../data/"
predictionCount = 3
DLM = "DL_MAPE"
FORECAST = "Forecast"
M2 = ["Spain"]  # Major 2
DL = "DL"
preds = "Predictions"
col_names_pred = [DATE, preds]
vdata_dir = "../vdata/"
rebasement = "rebasement"
optimizers = ["bfgs", "nm"]
models = [ARIMA, SARIMA, DL, SARIMAX]
