SARIMA = "SARIMA"
ARIMA = "ARIMA"
SARIMAX = "SARIMAX"
RMSE = "RMSE"
MSE = "MSE"
result_dir = "../results/"
MEAN = "Mean"
SOURCE = "Country + Energy"
DATE = "date"
data_dir = "../data/"
predictionCount = 3
ARIMAP = "arima_prediction"
SARIMAP = "sarima_prediction"
FORECAST = "Forecast"
M2 = ["France"]  # Major 2
preds = "Predictions"
col_names_pred = [DATE, preds]
vdata_dir = "../vdata/"
numberOfPredictions = 7
